name: generate-builds

on:
  push:
    branches: [ develop, main ]
  pull_request:
    branches: [ develop, main ]
  workflow_dispatch:

jobs:
  build-switch:
    name: build-switch
    runs-on: ubuntu-latest
    container: devkitpro/devkita64:latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Fix Git Directory Permissions
        run: |
          git config --global --add safe.directory /__w/Shipwright/Shipwright

      - name: Install Switch Dependencies
        run: |
          dkp-pacman -Sy --noconfirm switch-portlibs switch-libzip-archive switch-sdl2 switch-zlib switch-bzip2 switch-curl switch-mbedtls switch-libpng switch-glad switch-glm

      - name: Configure CMake
        run: |
          cmake -B build-switch -G Ninja \
            -DCMAKE_TOOLCHAIN_FILE=/opt/devkitpro/cmake/Switch.cmake \
            -DCMAKE_BUILD_TYPE=Release \
            -DPROJECT_BUILD_TYPE=Release

      - name: Build Project
        run: |
          cmake --build build-switch --config Release

      - name: Upload Switch Artifact
        uses: actions/upload-artifact@v4
        with:
          name: soh-switch
          path: |
            build-switch/soh.nro
