build-switch:
    name: build-switch
    runs-on: ubuntu-latest
    container: devkitpro/devkita64:latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Build SOH for Switch
        run: |
          mkdir build-switch && cd build-switch
          cmake -G Ninja -DCMAKE_TOOLCHAIN_FILE=/opt/devkitpro/cmake/Switch.cmake -DBUILD_SWITCH=ON ..
          ninja

      - name: Upload Switch Artifact
        uses: actions/upload-artifact@v3
        with:
          name: soh-switch
          path: |
            build-switch/soh.nro
