name: generate-builds

on:
  push:
    branches: [ develop, main ]
  pull_request:
    branches: [ develop, main ]
  workflow_dispatch:

jobs:
  build-switch:
    name: build-switch
    runs-on: ubuntu-latest
    container: devkitpro/devkita64:latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Fix Git Directory Permissions
        run: |
          git config --global --add safe.directory '*'

      - name: Build and Install libzip for Switch
        run: |
          git clone https://github.com/nih-at/libzip.git --depth 1
          cd libzip
          cmake -B build -G Ninja \
            -DCMAKE_TOOLCHAIN_FILE=/opt/devkitpro/cmake/Switch.cmake \
            -DCMAKE_INSTALL_PREFIX=/opt/devkitpro/portlibs/switch \
            -DBUILD_SHARED_LIBS=OFF \
            -DENABLE_COMMONCRYPTO=OFF \
            -DENABLE_GNUTLS=OFF \
            -DENABLE_MBEDTLS=OFF \
            -DENABLE_OPENSSL=OFF \
            -DBUILD_TOOLS=OFF \
            -DBUILD_EXAMPLES=OFF \
            -DBUILD_DOC=OFF
          ninja -C build install
          cd ..

      - name: Configure CMake
        run: |
          cmake -B build-switch -G Ninja \
            -DCMAKE_TOOLCHAIN_FILE=/opt/devkitpro/cmake/Switch.cmake \
            -DCMAKE_BUILD_TYPE=Release \
            -DPROJECT_BUILD_TYPE=Release \
            -DCMAKE_PREFIX_PATH=/opt/devkitpro/portlibs/switch

      - name: Build Project
        run: |
          cmake --build build-switch --config Release

      - name: Upload Switch Artifact
        uses: actions/upload-artifact@v4
        with:
          name: soh-switch
          path: |
            build-switch/soh.nro
